---
title: "Enable unit tests"
weight: 80
---

To enable unit tests in your pipeline there are two steps.

1. Edit `pipeline.yaml` and add commands to the test build step.
1. Commit and push these changes.

### Edit pipeline.yaml

Open up the `~/environment/sam-app/.github/workflows/pipeline.yaml` file in your editor. Search for the string `test:`. You will find a comment that shows where you can add commands to run your unit tests. Please add the commands that are appropriate for your chosen runtime.

::::tabs{variant="container" groupId=codeSample}
:::tab{id="Node" label="Node"}

```yaml
test:
  if: github.event_name == 'push'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        # trigger the tests here
        echo 'Running unit tests'
        cd hello-world
        npm install
        npm run test
```

:::
:::tab{id="Python" label="Python"}

```yaml
test:
  if: github.event_name == 'push'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        # trigger the tests here
        echo 'Running unit tests'
        pip3 install pytest pytest-mock
        python3 -m pytest tests/unit
```

:::
:::tab{id="Java" label="Java"}

```yaml
test:
    if: github.event_name == 'push'
    runs-on:  ubuntu-latest
    steps:
        - name: Check out Repository
          uses: actions/checkout@v3
        - name: Set up JDK
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'temurin'
        - name: Packaging Jar
          id: packaging-jar
          shell: bash
          run: cd HelloWorldFunction ; mvn clean install
```

:::

::::

### Commit and push changes

```bash
cd ~/environment/sam-app
git commit -am 'Enable unit tests in pipeline'
git push
```

### Watch the Workflow self-update and run tests

Open up your Workflow from the GitHub Actions dashboard. If you expand the `test` job, then you will see output from your new unit tests. Remember any change you make to the `pipeline.yaml` will be applied automatically once you commit.

![Output from the unit tests](/static/cicd-gh/workflow-tests.png)

**Congratulations! You have created a CI/CD pipeline for a Serverless application!**
